version: '3.7'

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile    
  
  tomcat:
    build:
      context: .
      dockerfile: DockerfileTomcat
    ports: 
      - "80:8080"  
      
  postgres:
    build:
      context: .
      dockerfile: DockerfilePostgres
    ports:
      - "5432:5432"