version: '3.9'

volumes:
  ubuntu:
    external: false
  tomcat:
    external: false

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile      
    volumes:
      - ubuntu:/usr/lamarrulla/appEngineLaMarrullaWS/target    
  
  tomcat:
    build:
      context: .
      dockerfile: DockerfileTomcat
    ports: 
      - "80:8080"
    volumes:
      - tomcat:/usr/local/tomcat/webapps    
      
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=maradr
    ports:
      - '5432:5432'
    