version: '3.7'

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile    
  
  tomcat:
    build:
      context: .
      dockerfile: DockerfileTomcat
    ports: 
      - "80:8080"  
      
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=maradr
    ports:
      - '5432:5432'